Fixed pitch shifting bug in SynthDef and add a parameter
musikinformatik/SuperDirt pull request #206
Opened 2020-07-26 21:55 UTC by thgrund

I have seen that there is a "dirt_pitch_shift" module in core_synths. Unfortunately it does not work as intended, because the pitch shift parameter "pitchRatio" in core_synths is called ``psratio`` and in core_modules ``psrate``. 
I fixed this typo (now it is called `psrate` everywhere) and was able to use it successfully on the tidal page.

I also added the timeDispersion parameter for PitchShift and named it `disp`.

2020-08-12 19:15 UTC, telephon requested changes
This looks very good, thank you! One request: a clearer name for `disp` would be `psdisp` – could you change this?

2020-08-12 21:10 UTC, thgrund commented
Sure, that's no problem. I renamed disp to psdisp. I like these clarification, because that way you can better associate psdisp with psrate.

2020-08-13 13:18 UTC, telephon approved these changes

2020-08-13 13:18 UTC, telephon commented
Thank you!

2020-08-13 13:19 UTC, merged