Improve error handling when loading samples
musikinformatik/SuperDirt pull request #272
Opened 2022-06-22 18:48 UTC by ahihi

adds a missing return and corrects a `try` call. fixes #266

2022-06-26 10:01 UTC, telephon requested changes
thanks! just one little thing …

2022-06-26 10:01 UTC, telephon commented on classes/DirtSoundLibrary.sc
>  				if(erreur.isException) { erreur.reportError };
Then, if we use the handler, no need to ask again if it is an exception, because the handler is only called if it is an exception. So this would be fine:

```
{ |erreur| erreur.reportError };
```

2022-06-26 11:34 UTC, ahihi commented
good point, fixed!

2022-06-27 20:19 UTC, telephon approved these changes

2022-06-27 20:20 UTC, merged