sum channels to avoid premature pause
musikinformatik/SuperDirt pull request #298
Opened 2023-12-03 16:20 UTC by redFrik

summing the sound channels (after rectification) makes sure that there's only a single DetectSilence and that no channel can pause the node prematurely.

this is a fix for a subtle bug in DirtPause. fixing it shouldn't affect sound except in some very rare corner cases. and then one would want the fix applied anyways i guess.

issue demonstrated here using rms but same problem can be found in all places where DirtPause is used. e.g. reverbs stopping early.

```supercollider
SuperDirt.start;
~d1 = ~dirt.orbits[0];
~dirt.startSendRMS;

//with default graceTime 4 the following should finish around 9
//i.e. dirt_rms node pauses itself and stop sending messages
(
var start= Main.elapsedTime;
OSCdef(\rms, {|msg, time| (time-start).postln}, "/rms");
~d1.((sound: 'tutorial2', dur: 5, pan: 0.5));
)

//same code panned hard right.
//note: it will finish early - around 8!
(
var start= Main.elapsedTime;
OSCdef(\rms, {|msg, time| (time-start).postln}, "/rms");
~d1.((sound: 'tutorial2', dur: 5, pan: 1));
)

the silent left channel stopped dirt_rms node sending 1sec early.
with the proposed fix the two examples both hold the full duration.

```

2024-09-05 08:53 UTC, yaxu commented
I've only just spotted this, sorry @redFrik ! Does this look good to merge @telephon ?

2024-09-11 12:45 UTC, telephon requested changes
good catch, thanks @redFrik !
It should be `signal.abs.asArray.sum` though, because sometimes, one may pass just a mono signal.

2024-09-12 21:57 UTC, redFrik commented
yes, i hadn't considered mono signals. now corrected. thanks @telephon

2024-09-13 10:13 UTC, telephon approved these changes

2024-09-13 10:13 UTC, merged

2024-09-13 10:13 UTC, telephon commented
Thank you, @redFrik !!