Active / deactive global effects
musikinformatik/SuperDirt pull request #305
Opened 2024-09-15 09:49 UTC by telephon

Allow us to activate and deactivate global effects.

This fixes #299.

2024-09-28 19:09 UTC, telephon commented on classes/GlobalDirtEffect.sc
> +		if(active) {
actually, this may not be needed. It is ok, to have a paused synth in there. I'll fix this.

2024-09-28 19:31 UTC, telephon commented
OK, maybe you can check this?

2024-09-30 19:15 UTC, thgrund commented
> OK, maybe you can check this?

I am eager to help :-) 
More details here: https://github.com/musikinformatik/SuperDirt/pull/307#issuecomment-2383967186

But we can continue the discussion in this PR.

2024-10-03 10:15 UTC, thgrund commented
Hey @telephon ! So in general the changes are doing what I expect. But there is one issue, that we faced during our tests.

It looks like, that there is a race condition between the evaluation of the `active` and the `set` function.  This can be reproduced with a simple example: 

Single note example in TidalCycles
```
  d1 $ s "superpiano" <| note "c" # room 0.8 # sz 0.8
 ```

When you activate and deactivate the reverb effect in SuperCollider in between the not events, then everything works flawless: 
```
 ~dirt.orbits[0].globalEffects[4].active_(true) -- assuming the reverb effect is on the fifth position
~dirt.orbits[0].globalEffects[4].active_(false) -- assuming the reverb effect is on the fifth position
```

But when you try the same with i.e. more notes (or simply when more events will be send), then sometimes the effect will be resumed immediately, event when the active property is false. Like in this example: 

```
  d1 $ s "superpiano" <| note "c*32" # room 0.8 # sz 0.8
```

2024-10-14 11:47 UTC, thgrund commented
@telephon can I help here to speed up this Pull Request? As in my (Pull Request)[https://github.com/musikinformatik/SuperDirt/pull/307#issuecomment-2383967186], I would recommend to not execute `set` if the global effect is not active. If you don't want to do that directly inside of `GlobalDirtEffect.sc`, then you could check the flag when `set` is called inside of `setGlobalEffects` in `DirtOrbit`.

WDYT?

2024-10-16 19:03 UTC, telephon commented
Hi @thgrund I'll return to this next week – thank you for your testing and of course also the reminder.
For now, one question:

The race condition happens when you are toggling the effects while you play notes from tidal, right?

2024-10-18 13:11 UTC, thgrund commented
Hey @telephon thanks for letting me know :-) 

> The race condition happens when you are toggling the effects while you play notes from tidal, right?

Exactly!

2024-10-18 16:15 UTC, telephon commented
I've just made a change, could you check if it fixes your issue?

2024-10-22 18:33 UTC, thgrund commented
I finished my tests and I am a little confused now. The race condition still exists. I do not fully understand why this happens, but from the code perspective this looks good. I tried it with my compressor effect and with the default reverb effect. 

Here is an example with some debug messages, where I logged the function calls in `GlobalDirtEffect.sc`: 

```
set; active: true, fxName: dirt_global_compressor
resume; active: true, fxName: dirt_global_compressor
set; active: true, fxName: dirt_global_compressor
resume; active: true, fxName: dirt_global_compressor
active_; flag: false, fxName: dirt_global_compressor
pause; active: false, fxName: dirt_global_compressor, synth: Synth('dirt_global_compressor2' : 1200)
set; active: false, fxName: dirt_global_compressor
set; active: false, fxName: dirt_global_compressor
set; active: false, fxName: dirt_global_compressor
set; active: false, fxName: dirt_global_compressor
set; active: false, fxName: dirt_global_compressor
```

But the effect was not bypassed reliable when I send TidalCycles events. Another interesting aspect is, that when I changed the `set` function like this: 

```
          set { |event|
                  var argsChanged, someArgsNotNil = alwaysRun;
                  if(active) {
                          paramNames.do { |key|
                                  var value = event[key];
                                  value !? { someArgsNotNil = true };
                                  if(state[key] != value) {
                                          argsChanged = argsChanged.add(key).add(value);
                                          state[key] = value;
                                  }
                          };
                          if(someArgsNotNil) { this.resume };
                          if(argsChanged.notNil and: { synth.notNil }) {
                                  synth.set(*argsChanged);
                          }
                  } {
                      this.pause;
                  }
```

Then I hear the synth bypassed when I call active_(false) on the effect, then it gets active again for a short amount of time and then it finally get paused. Could it be, that the pause action on the server side takes some time on more complex SynthDefs and when this happens, then the client code is not applied like we expect it?

2024-10-23 14:46 UTC, telephon commented
> Could it be, that the pause action on the server side takes some time on more complex SynthDefs and when this happens, then the client code is not applied like we expect it?

no, I don't think so, pausing is very fast. The mistake is probably in the interaction of the three following things:
1. resuming of self-paused synths (global effect synths pause themselves when not used)
2. resuming of explictly paused synths
3. pausing of running synths and setting the active flag= true

2024-10-23 14:53 UTC, telephon commented
Just to reduce the possibilities of wrong ordering, I've added a little change.

2024-10-26 19:28 UTC, thgrund commented
Hey @telephon , I faced an issue with the changes you made in the `resume` function. To solve this, I changed it locally in this way: 

```
resume {
	synth.server.sendBundle(nil,
		['/n_run', synth.nodeID, 1],
		['/n_set', synth.nodeID, 'resumed', 1]
	);
}
``` 

I will do my investigation in parallel and will inform you, when I find something.

2024-10-26 20:37 UTC, telephon commented
Thanks for the catch, I am sorry I didn't check carefully enough.

Also, I've added a change so that the synth is registered. You should be able to check if it is running or not (there is, of course a tiny delay between the state change in scsynth and the state change in sclang).

```supercollider
a = ~dirt.orbits[0].globalEffects[0];
a.isPlaying; // exists or not
a.isRunning; // paused or not
```

2024-10-26 20:38 UTC, telephon commented
> Or to be more precise, when I check the synth whether it is playing or running, then the value is always false. I will keep trying it.

Yes, this is the case when you don't register them explicitly.

2024-10-27 20:22 UTC, thgrund commented
Hey @telephon . Here are some test results for one effect for one orbit where you can see, that sometimes the synth will be paused, and sometimes it's not running. What I learned from these examples is, that the action calls from the client sides are exactly the same (active, pause, set). But the result differs. At this point I would expect, that the error happens on the server side. 

This is the success case:
```
// active = true (works)
active; flag: true; synth status: true
resumed; synth status: true

// usual set for active synth (works)
before set; synth status: true; active: true
resumed; synth status: true
set; synth status: true

// active = false
active; flag: false; synth status: true
pause; synth status: true

// set call - no calculation (first one may be caused by server response delay)
before set; synth status: true; active: false
before set; synth status: false; active: false
before set; synth status: false; active: false
before set; synth status: false; active: false
before set; synth status: false; active: false
```

Error case (synth keeps running):
```
// active = true (works) - synth status = false -> server delay
active; flag: true; synth status: false
resumed; synth status: false

// usual set for active synth (works)
before set; synth status: true; active: true
resumed; synth status: true
set; synth status: true

// active = false
active; flag: false; synth status: true
pause; synth status: true

//*******************************
// HERE THE ERROR HAPPENS
//*******************************
//
// set call - no calculation; but synth runs and active = false
before set; synth status: true; active: false
before set; synth status: true; active: false
before set; synth status: true; active: false
before set; synth status: true; active: false
```

2024-10-27 22:09 UTC, telephon commented
This is excellent, thank you for the good analysis. Just one question, what is meant by "synth status: true"? That it is playing (exists on the server), but may be paused (then active=false)?

2024-10-28 05:56 UTC, thgrund commented
Ah sorry, this was not clear. The synth status is the value of `isRunning`. Because the Node always exists, means `isPlaying` always true. This is why I just printed the value of `synth.isRunning` for one effect. Basically like this: 
```
format("resumed; synth status: %", synth.isRunning).postln;}
```

2024-10-28 07:56 UTC, telephon commented
So yes, this is clearly a timing issue, the synth is woken up after it is paused explicitl by a message that is already on its way.
I have done two things: use an existing pauseImmediately parameter and add the standard latency to the osc messages, so they come late enough.

Could you please check again? Sorry, this is a little tricky.

2024-10-28 18:08 UTC, thgrund requested changes
Nice! Adding the synth server latency resolves the issue! 🥳

2024-10-28 18:08 UTC, thgrund commented on classes/GlobalDirtEffect.sc
>  			['/n_run', synth.nodeID, 1]
Here is a missing comma.

2024-10-28 18:08 UTC, thgrund commented on classes/GlobalDirtEffect.sc
> +		synth.server.sendBundle(nil,
We need to add the condition again (`if(synth.notNil) {...}`)

2024-10-29 11:07 UTC, thgrund commented on classes/SuperDirtUGens.sc
> +		"DirtPause % running".format(UGen.buildSynthDef.name).poll(2);
And I think this line can be removed now?

2024-10-30 09:21 UTC, telephon commented
if all works, I'd merge into develop now.

2024-10-30 09:56 UTC, thgrund commented
I just checked it again and from my end everything works fine now :-)

2024-10-30 13:54 UTC, merged